# general configuration applicable to the entire app
general:
  name: llama3.1-8b-g5

defaults: &ec2_settings
  region: {{region}}
  ami_id: {{gpu}}
  device_name: /dev/sda1
  ebs_del_on_termination: True
  ebs_Iops: 16000
  ebs_VolumeSize: 250
  ebs_VolumeType: gp3
  startup_script: startup_scripts/ubuntu_startup.txt
  post_startup_script: post_startup_scripts/fmbench.txt
  # Timeout period in Seconds before a run is stopped
  fmbench_complete_timeout: 2400
  
instances:
- instance_type: g5.xlarge
  deploy: yes
  <<: *ec2_settings
  fmbench_config: 
  - fmbench:llama3.1/8b/config-llama3.1-8b-g5.xl-tp-1-mc-max-ec2-conc-1-2.yml

- instance_type: g5.2xlarge
  deploy: yes
  <<: *ec2_settings
  fmbench_config: 
  - fmbench:llama3.1/8b/config-llama3.1-8b-g5.2xl-tp-1-mc-max-ec2-conc-1-2.yml


