# general configuration applicable to the entire app
general:
  name: llama3.1-8b-g6e-p5-djl

defaults: &ec2_settings
  region: {{region}}
  ami_id: {{gpu}}
  device_name: /dev/sda1
  ebs_del_on_termination: True
  ebs_Iops: 16000
  ebs_VolumeSize: 250
  ebs_VolumeType: gp3
  startup_script: startup_scripts/ubuntu_startup.txt
  post_startup_script: post_startup_scripts/fmbench.txt
  # Timeout period in Seconds before a run is stopped
  fmbench_complete_timeout: 2400
  
instances:
- instance_type: g6e.2xlarge
  deploy: yes
  <<: *ec2_settings
  fmbench_config: 
  - fmbench:llama3.1/8b/config-llama3.1-8b-g6e.2xl-tp-1-mc-max-djl.yml

- instance_type: g6e.4xlarge
  deploy: yes
  <<: *ec2_settings
  fmbench_config: 
  - fmbench:llama3.1/8b/config-llama3.1-8b-g6e.4xl-tp-1-mc-max-djl.yml

- instance_type: g6e.12xlarge
  deploy: yes
  <<: *ec2_settings
  fmbench_config: 
  - fmbench:llama3.1/8b/config-llama3.1-8b-g6e.12xl-tp-2-mc-max-djl.yml
  - fmbench:llama3.1/8b/config-llama3.1-8b-g6e.12xl-tp-4-mc-max-djl.yml

- instance_type: g6e.24xlarge
  deploy: yes
  <<: *ec2_settings
  fmbench_config: 
  - fmbench:llama3.1/8b/config-llama3.1-8b-g6e.24xl-tp-2-mc-max-djl.yml
  - fmbench:llama3.1/8b/config-llama3.1-8b-g6e.24xl-tp-4-mc-max-djl.yml

- instance_type: g6e.48xlarge
  deploy: yes
  <<: *ec2_settings
  fmbench_config: 
  - fmbench:llama3.1/8b/config-llama3.1-8b-g6e.48xl-tp-2-mc-max-djl.yml
  - fmbench:llama3.1/8b/config-llama3.1-8b-g6e.48xl-tp-4-mc-max-djl.yml
  - fmbench:llama3.1/8b/config-llama3.1-8b-g6e.48xl-tp-8-mc-max-djl.yml

- instance_type: p5.48xlarge
  deploy: no
  <<: *ec2_settings
  fmbench_config: 
  - fmbench:llama3.1/8b/config-ec2-llama3-1-8b-p5-tp-2-mc-max.yml
