# general configuration applicable to the entire app
general:
  name: llama3.1-70b-summarization

instances:
# This is for a capacity reservation type instance p4de.24xlarge
- instance_type: p4de.24xlarge
  deploy: yes
  region: us-west-2
  ami_id: {{ gpu }}
  device_name: /dev/sda1
  ebs_del_on_termination: True
  ebs_Iops: 16000
  ebs_VolumeSize: 400
  ebs_VolumeType: gp3
  #Defaults to none, You can use either Reservation Id ARN or both
  CapacityReservationPreference: 
  CapacityReservationId: cr-0aed3d7ec3ff92812
  CapacityReservationResourceGroupArn:
  startup_script: startup_scripts/ubuntu_startup.txt
  post_startup_script: post_startup_scripts/fmbench.txt
  # Timeout period in Seconds before a run is stopped
  fmbench_complete_timeout: 6000
  fmbench_config: 
  - fmbench:llama3.1/70b/config-ec2-llama3-1-70b-p4de.24xl-deploy-ec2-summarization.yml
  upload_files:
  - local: byo_dataset/synthetic_data_large_prompts.jsonl
    remote: /tmp/fmbench-read/source_data
  - local: byo_dataset/prompt_template_llama3_summarization.txt
    remote: /tmp/fmbench-read/prompt_template/prompt_template_llama3_summarization.txt

